#!/bin/bash
echo "Welcome to the LLM Auditor Agent!"
echo ""
echo "To get started, you'll need to set up your environment variables."
echo "Copy the .env.example file to .env and fill in the values:"
echo ""
echo "cp .env.example .env"
echo ""
echo "Then, you can run the agent using the following command:"
echo ""
echo "poetry run python -m llm_auditor.main"
echo ""
